name: Deploy to Server
on:
  push:
    branches:
      - prod 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0 

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Check Output Directory
        run: ls -la ./

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /volume1/web/htdocs/hasethblog/app
            rm -rf *
            git clone --depth=1 https://hasecom:${{ secrets.YOUR_PAT_SECRET }}@github.com/hasecom/hasethblog-app-qr.git -b prod out
            ls -la ./out
