name: Deploy to Server
on:
  push:
    branches:
      - prod 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Check commit message and decide
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "Commit message: $commit_message"

          if [[ "$commit_message" == *"[deploy]"* ]]; then
            echo "Commit message contains '[deploy]'. Proceeding with the workflow."

            # [deploy] ブランチに対するステップを追加
            npm install
            npm run build

          else
            echo "Commit message does not contain '[deploy]'. Skipping workflow."
            exit 78  # Exit code 78 はワークフローのスキップを示します

      - name: Update prod branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Update prod branch with build artifacts [skip ci]"
          git push origin HEAD:prod