name: Deploy to Server
on:
  push:
    branches:
      - prod 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0 

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy via SFTP
        run: |
          scp -r -P ${{ secrets.SSH_PORT }} ./out/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/volume1/web/htdocs/hasethblog/app/
        env:
          SFTP_PASSWORD: ${{ secrets.SSH_PASSWORD }}
