name: Deploy to Server
on:
  push:
    branches:
      - prod 

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        env:
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0 

      - name: Install Dependencies
        run: | 
          npm install
          npm install --save-dev next-sitemap

      - name: Configure Git Identity
        run: |
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git config user.name "${{ secrets.GIT_USERNAME }}"

      - name: Build
        run: |
          next build
          pwd
          ls -la
          git status

      - name: Push to Swap Branch
        run: |
          git add .
          git commit -m "github Actions"
          git push -f origin HEAD:swap
        env:
          token: ${{ secrets.GITHUB_TOKEN }} 
    
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /home/hasecom/hasethblog.com/public_html/qr
            ls -la
            rm -rf front
            git clone --depth=1 https://hasecom:${{ secrets.YOUR_PAT_SECRET }}@github.com/hasecom/hasethblog-app-qr.git -b swap front/temp
            ls -la
            mv front/temp/out/* front/
            rm -rf front/temp
            ls -la