name: Deploy to Server
on:
  push:
    branches:
      - prod 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0 

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Check Output Directory
        run: ls -la ./

      - name: Push to origin/swap
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git checkout -b swap
          git add .
          git commit -m "Build artifacts"
          git push -u origin swap

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /volume1/web/htdocs/hasethblog/app
            ls -la
            rm -rf *
            git clone --depth=1 https://hasecom:${{ secrets.YOUR_PAT_SECRET }}@github.com/hasecom/hasethblog-app-qr.git -b swap front/temp
            ls -la front/temp/out/_next/static/chunks/
            ls -la
            mv front/temp/out/* front/
            rm -rf front/temp
            ls -la