name: Deploy to Server
on:
  push:
    branches:
      - prod 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Check commit message and decide
        run: |
          if [[ "$(git log -1 --pretty=%B)" == *"[deploy]"* ]]; then
            echo "Commit message contains '[deploy]'. Proceeding with the workflow."

            # Add steps for [deploy] branch
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18.19.0 

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: npm run build

          else
            echo "Commit message does not contain '[deploy]'. Skipping workflow."
            exit 78  # Exit code 78 skips the workflow

      - name: Update prod branch
        run: |
          git add -A
          git commit -m "Update prod branch with build artifacts"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "${GITHUB_ACTOR}"
          git push origin HEAD:prod

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /volume1/web/htdocs/hasethblog/app
            ls -la
            rm -rf *
            git clone --depth=1 https://hasecom:${{ secrets.YOUR_PAT_SECRET }}@github.com/hasecom/hasethblog-app-qr.git -b prod front/temp
            ls -la front/temp/out/_next/static/chunks/
            ls -la
            mv front/temp/out/* front/
            rm -rf front/temp
            ls -la